version: '3'
services:
  node-backend:
    build:
      context: .
      dockerfile: Dockerfile  # Usar el Dockerfile del contexto para Node.js
    container_name: node_backend
    ports:
      - "${PORT}:${PORT}"  # Puerto leído de la variable de entorno
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production  # La aplicación se ejecuta en modo de producción (rendimiento optimizado, no instala dependencias de desarrollo).
    env_file:
      - .env  # Cargar las variables de entorno del archivo .env

  python-backend:
    build:
      context: ./src/python  # El directorio donde está tu código Python
      dockerfile: Dockerfile  # El Dockerfile de Python
    container_name: python_backend
    ports:
      - "${SERVICEPY_PORT}:${SERVICEPY_PORT}"  # Mapea el puerto de Python desde la variable .env
    volumes:
      - ./src/python:/app  # Monta el código fuente de Python en el contenedor
    env_file:
      - .env  # Cara variables de entorno